
language: c
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libatlas-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/openblas ; fi

script:
  - ./configure --with-precision=single && make && make test
  - ./configure --with-precision=double && make && make test
  - gcov -o build/CMakeFiles/test_bin.dir/src/main.gcno src/main.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
