
language: c
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - gfortran
      - libatlas-dev

script:
  - ./configure --with-precision=single && make && make test
  - ./configure --with-precision=double && make && make test
