#######################################################################
# Makefile generated by './configure' at Sat Jun 18 16:14:42 CDT 2016
# Using flags:
#######################################################################

all clean test:
	make -C build $@ $(MAKEFLAGS)

distclean:
	rm -rf build Makefile

