#######################################################################
# Makefile generated by './configure' at Sat Jun 18 16:50:50 CDT 2016
# Using flags:
#	-DFLT_WIDTH=single
#######################################################################

all clean test:
	make -C build $@ $(MAKEFLAGS)

distclean:
	rm -rf build Makefile

